### ISSUE TITLE
Cannot create new 'Player' actors due to Starting Equipment issues!

### ISSUE THREAD

**Issue by WildBillLives** [Cussa/fvtt-true-d6#4]
When I try to create a new 'Player' actor it fails and I get the following error message in the console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toObject')
[Detected 1 package: system:trued6(0.0.5)]
    at actor.mjs:143:99
    at async Promise.all (index 0)
    at async Trued6Actor._preCreate (actor.mjs:143:17)
    at async #preCreateDocumentArray (foundry.js:13541:21)
    at async ClientDatabaseBackend._createDocuments (foundry.js:13428:22)
    at async Trued6Actor.createDocuments (commons.js:7958:23)
    at async Trued6Actor.create (commons.js:8081:23)
```
I can create NPCs just fine, but Player actors will not be created. 

Also, I cannot clear my 'Starting Equipment'  list, when I hit the 'trash can' icon nothing happens and no errors are thrown in the console.

My starting equipment is listed as a single item with the following text:  "Coin purse, backpack, bedroll, small tent, blanket, flint and steel, 3 x torches, bandages, waterskin, food rations, cooking set, travel clothes, leather belt. "

This is in Foundry v11.315, TrueD6 system version v0.0.5, and no other modules loaded.

**Comment by Cussa** [comment]
Hi @WildBillLives , I hope you are doing well.

I am trying to reproduce here but I am not able too. The starting equipment has to be valid on the world. Did you deleted the item from the world?

That would explain both issues that you are having: the not able to delete and the actor failing to be created.

If you deleted the item, please, run the following command to clear the information:

```js
await game.settings.set("trued6", "startingEquipment", [])
```
That should clear the starting equipment selection and allow you to make it work again.

Let me know if that worked, so I can close the bug :)

Many thanks

**Comment by WildBillLives** [comment]
Yes! I had apparently recreated the starting equipment item after it was deleted, but the original item (with a different ID) was still listed in the Starting Equipment form. Your code fixed it perfectly, thanks!
