### ISSUE TITLE
Query regarding initiative...

### ISSUE THREAD

**Issue by WildBillLives** [Cussa/fvtt-true-d6#5]
Please ignore and close...it was a module that was causing the initiative order to go all 'wonky', it works fine as implemented.

**Comment by WildBillLives** [comment]
Not an issue, my apologies...

**Comment by Cussa** [comment]
Hey! No worries about posting this here.

You can find me on the Nerdura Discord server, and many other servers 😄 

Happy to help if you see something! 👍

**Comment by WildBillLives** [comment]
Could I get an invite to the Nerdura discord?   

TrueD6 is my new 'favorite fantasy system', and I've been playing RPGs since 1977 (yeah, I'm an old codger...LOL)

**Comment by Cussa** [comment]
Here you go: https://discord.gg/R433VPHW
